spring:
  datasource:
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    driverDialect: org.hibernate.dialect.H2Dialect
#    url: jdbc:h2:file:./db/fs_server
#    username: SYSDBA
#    password: masterhost
#    driverClassName: org.firebirdsql.jdbc.FBDriver
#    driverDialect: org.hibernate.dialect.FirebirdDialect
#    url: jdbc:firebirdsql://localhost:3050/C:\Users\admin\Downloads\FileServer\FileServer\db\server.fdb
    username: kzm_vlad
    password: 123root@
    driverClassName: com.mysql.cj.jdbc.Driver
    driverDialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/fs_server_db
  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true


server:
  port: 36792

logging:
  level:
    root: INFO

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
